origin_webrtc_teleop:
  ros__parameters:
    local_id: "origin"
    hostname: "127.0.0.1"
    port: "8000"
    stun_server: "stun:stun.l.google.com:19302"
    video_encoder:
      bit_rate: 1000000
      width: 640
      height: 480
      framerate: 30
      gop_size: 10
      max_b_frames: 0
      refs: 1
      options:
        preset: "ultrafast"
        tune: "zerolatency"