FROM ros:humble

ENV ROS_LOCALHOST_ONLY=1

WORKDIR /root/ws

RUN apt-get update && apt-get install -y \
    libavcodec-dev \
    libavutil-dev \
    libswscale-dev \
    libavformat-dev \
    git \
    cmake \
    build-essential \
    pkg-config \
    nlohmann-json3-dev \
    libusb-1.0-0-dev \
    libssl-dev \
    libgtk-3-dev \
    libglfw3-dev \
    libglew-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p external/libdatachannel \
    && git clone https://github.com/paullouisageneau/libdatachannel.git /root/ws/external/libdatachannel \
    && cd /root/ws/external/libdatachannel \
    && git submodule update --init --recursive --depth 1 \
    && cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/humble \
    && cd build \
    && make -j2 \
    && make install

# Build librealsense
ARG LIBREALSENSE_VERSION=2.53.1
RUN git clone https://github.com/IntelRealSense/librealsense.git \
    && cd librealsense \
    && git checkout v${LIBREALSENSE_VERSION} \
    && mkdir build && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false \
    && make -j$(($(nproc)-1)) \
    && make install \
    && rm -rf /root/ws/librealsense

# Build realsense-ros
ARG REALSENSE_ROS_VERSION=4.54.1
RUN mkdir -p /root/ws/src \
    && cd /root/ws/src \
    && git clone https://github.com/IntelRealSense/realsense-ros.git -b ${REALSENSE_ROS_VERSION} \
    && cd /root/ws \
    && . /opt/ros/humble/setup.sh \
    && colcon build --symlink-install --packages-select realsense2_camera realsense2_description

COPY . /root/ws/src/origin_webrtc_teleop

RUN . /opt/ros/humble/setup.sh && \
    colcon build --packages-select origin_webrtc_teleop

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc && \
    echo "source /root/ws/install/setup.bash" >> ~/.bashrc

CMD ["tail", "-f", "/dev/null"]