version: '3'
services:
  webrtc_teleop:
    build:
      context: ..
      target: prod
      dockerfile: docker/Dockerfile
    container_name: webrtc_teleop
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - /data/app/avular/dds:/dds