version: '3'
services:
  webrtc_teleop:
    build:
      context: ..
      target: dev
      dockerfile: docker/Dockerfile
    container_name: webrtc_teleop_dev
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb